name: Makefile-src CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Makefile'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Makefile'
      - 'CMakeLists.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
